# Generated by Django 5.2.5 on 2025-08-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=16, null=True, verbose_name='Телефон')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='doctors/photos/', verbose_name='Фотография')),
                ('qualification', models.CharField(max_length=255, verbose_name='Квалификация')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Стаж (лет)')),
                ('education', models.CharField(blank=True, max_length=255, null=True, verbose_name='Образование')),
                ('place_of_work', models.CharField(blank=True, max_length=255, null=True, verbose_name='Место работы')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность')),
                ('specializations', models.CharField(blank=True, max_length=255, null=True, verbose_name='Специализации')),
                ('certificates', models.TextField(blank=True, null=True, verbose_name='Сертификаты, лицензии')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Биография, информация о себе')),
                ('achievements', models.TextField(blank=True, null=True, verbose_name='Достижения')),
                ('consultation_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость консультации')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
            ],
            options={
                'verbose_name': 'Врач',
                'verbose_name_plural': 'Врачи',
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название квалификации')),
            ],
        ),
    ]
